version: '3'

services:
  php:
    container_name: "php74"
    build: ./php
    ports:
      - "9000:9000"
    restart: always
    user: 0:0
    volumes:
        - ./nginx/data/www:/usr/share/nginx/html
    stdin_open: true
    tty: true
    links:
      - "mysql"
    networks:
        app_net:
            ipv4_address: 10.10.10.3
    environment:
        - TZ=Asia/Shanghai
  nginx:
    container_name: "nginx"
    image: nginx:1.10
    restart: always
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - "php"
    links:
      - "php:php74"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf #配置文件挂载
      - ./nginx/conf/conf.d:/etc/nginx/conf.d #配置文件挂载
      - ./nginx/data/www:/usr/share/nginx/html:rw #静态资源根目录挂载
      - ./nginx/data/log:/var/log/nginx #日志文件挂载
    networks:
      app_net:
        ipv4_address: 10.10.10.2
  mysql:
    container_name: "mysql"
    image: mysql:5.7
    ports:
      - "13306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/data/mysql/logs
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      app_net:
        ipv4_address: 10.10.10.1

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      config:
        - subnet: 10.10.0.0/16